### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by richardtape** [casinthecloud/casinthecloud#1]
Hi!

Thanks so much for putting this together. I'm just in the process of getting this all to work locally. I ran `./package.sh` and then `docker-compose up` (I've chosen to use the compose file with cas management). Everything starts up as expected. I've added the necessary lines to my hosts file and then navigate to http://cas-server:8080/

As expected, I'm redirected to http://cas-server:8080/login and can see the sign in screen.

Upon trying either of the recommended user/pass combinations;

i.e.

u: leleuj
p: leleuj

or 

u: jleleu
p: jleleu

CAS tells me I have invalid credentials.

Also, in the container logs, I see

`017-12-05 20:20:42,392 ERROR [org.apereo.cas.web.flow.AuthenticationExceptionHandler] - <Unable to translate handler errors of the authentication exception org.apereo.cas.authentication.AuthenticationException: 0 errors, 0 successes. Returning UNKNOWN by default...>`

I'm almost certainly being stupid, but can you let me know, just for my local testing environment, how I could set up some very simple username/password sign in (Ideally I'd like custom properties but I can hopefully work that out after I have the simple username/password working)

Thanks again!

**Comment by richardtape** [comment]
Just wanted to follow up on this. I've come back to this project 3 months later, and I'm still having the same issue. @leleuj would you have any idea why this would be the case?

**Comment by leleuj** [comment]
Unfortunately, I haven't had time to work on this, I had planned to offer some CAS server packaged for the cloud, but maybe this will happen later this year.
If you are looking for a CAS server example, you may want to use this project: https://github.com/apereo/cas-overlay-template
